// src/components/SeasonalPricing.tsx
import React, { useState, useEffect } from 'react';

// Mock function to fetch predefined seasons (replace with actual API call)
const fetchPredefinedSeasons = async () => {
  // Simulated API response
  return [
    { id: 1, ChartName: 'Default 2023', Level: 1, DateStart: '2023-01-01', DateEnd: '2023-03-31', Description: 'Low Season' },
    { id: 2, ChartName: 'Default 2023', Level: 2, DateStart: '2023-04-01', DateEnd: '2023-06-30', Description: 'Mid Season' },
    { id: 3, ChartName: 'Default 2023', Level: 3, DateStart: '2023-07-01', DateEnd: '2023-08-31', Description: 'High Season' },
    { id: 4, ChartName: 'Default 2023', Level: 2, DateStart: '2023-09-01', DateEnd: '2023-12-31', Description: 'Mid Season' },
  ];
};

export const SeasonalPricing = ({ onNext, onPrev, updateFormData }) => {
  const [seasons, setSeasons] = useState([]);
  const [currency, setCurrency] = useState('GBP');
  const [predefinedSeasons, setPredefinedSeasons] = useState([]);
  const [selectedChart, setSelectedChart] = useState('');

  useEffect(() => {
    const loadPredefinedSeasons = async () => {
      const fetchedSeasons = await fetchPredefinedSeasons();
      setPredefinedSeasons(fetchedSeasons);
      const chartNames = [...new Set(fetchedSeasons.map(season => season.ChartName))];
      if (chartNames.length > 0) {
        setSelectedChart(chartNames[0]);
      }
    };
    loadPredefinedSeasons();
  }, []);

  const handleChartSelection = (chartName) => {
    setSelectedChart(chartName);
    const selectedSeasons = predefinedSeasons
      .filter(season => season.ChartName === chartName)
      .map(season => ({
        id: season.id,
        name: season.Description,
        startDate: season.DateStart,
        endDate: season.DateEnd,
        nightlyRate: '',
        weeklyRate: ''
      }));
    setSeasons(selectedSeasons);
  };

  const handleSeasonChange = (id, field, value) => {
    setSeasons(prevSeasons =>
      prevSeasons.map(season =>
        season.id === id ? { ...season, [field]: value } : season
      )
    );
  };

  const addCustomSeason = () => {
    const newId = Math.max(...seasons.map(s => s.id), 0) + 1;
    setSeasons([...seasons, { id: newId, name: 'Custom Season', startDate: '', endDate: '', nightlyRate: '', weeklyRate: '' }]);
  };

  const removeSeason = (id) => {
    setSeasons(seasons.filter(season => season.id !== id));
  };

  const calculateWeeklyRate = (nightlyRate) => {
    return (parseFloat(nightlyRate) * 7).toFixed(2);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    updateFormData({ seasons, currency, chartName: selectedChart });
    onNext();
  };

  return (
    <div className="max-w-4xl mx-auto">
      <h2 className="text-2xl font-bold mb-4">Seasonal Pricing</h2>
      
      <div className="mb-4">
        <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="currency">
          Currency
        </label>
        <select
          id="currency"
          value={currency}
          onChange={(e) => setCurrency(e.target.value)}
          className="shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
        >
          <option value="GBP">Pounds Sterling (£)</option>
          <option value="EUR">Euros (€)</option>
        </select>
      </div>

      <div className="mb-4">
        <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="chartSelection">
          Select Predefined Season Chart
        </label>
        <select
          id="chartSelection"
          value={selectedChart}
          onChange={(e) => handleChartSelection(e.target.value)}
          className="shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
        >
          {[...new Set(predefinedSeasons.map(season => season.ChartName))].map(chartName => (
            <option key={chartName} value={chartName}>{chartName}</option>
          ))}
        </select>
      </div>

      {seasons.map((season) => (
        <div key={season.id} className="mb-6 p-4 border rounded">
          <div className="flex justify-between items-center mb-2">
            <input
              type="text"
              value={season.name}
              onChange={(e) => handleSeasonChange(season.id, 'name', e.target.value)}
              placeholder="Season Name"
              className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
            />
            <button
              onClick={() => removeSeason(season.id)}
              className="ml-2 bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
            >
              Remove
            </button>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <input
              type="date"
              value={season.startDate}
              onChange={(e) => handleSeasonChange(season.id, 'startDate', e.target.value)}
              className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
            />
            <input
              type="date"
              value={season.endDate}
              onChange={(e) => handleSeasonChange(season.id, 'endDate', e.target.value)}
              className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
            />
          </div>
          <div className="grid grid-cols-2 gap-4 mt-2">
            <div>
              <label className="block text-gray-700 text-sm font-bold mb-2">
                Nightly Rate ({currency === 'GBP' ? '£' : '€'})
              </label>
              <input
                type="number"
                value={season.nightlyRate}
                onChange={(e) => {
                  const nightlyRate = e.target.value;
                  handleSeasonChange(season.id, 'nightlyRate', nightlyRate);
                  handleSeasonChange(season.id, 'weeklyRate', calculateWeeklyRate(nightlyRate));
                }}
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
              />
            </div>
            <div>
              <label className="block text-gray-700 text-sm font-bold mb-2">
                Weekly Rate ({currency === 'GBP' ? '£' : '€'})
              </label>
              <input
                type="number"
                value={season.weeklyRate}
                readOnly
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline bg-gray-100"
              />
            </div>
          </div>
        </div>
      ))}

      <button
        type="button"
        onClick={addCustomSeason}
        className="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline mb-4"
      >
        Add Custom Season
      </button>

      <div className="flex items-center justify-between mt-6">
        <button
          type="button"
          onClick={onPrev}
          className="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
        >
          Previous
        </button>
        <button
          type="submit"
          onClick={handleSubmit}
          className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
        >
          Next
        </button>
      </div>
    </div>
  );
};

// src/app/components/seasonal-pricing/seasonal-pricing.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, FormArray, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { ContractDataService } from '../../services/contract-data.service';

@Component({
  selector: 'app-seasonal-pricing',
  templateUrl: './seasonal-pricing.component.html',
  styleUrls: ['./seasonal-pricing.component.scss'],
})
export class SeasonalPricingComponent implements OnInit {
  pricingForm: FormGroup;
  predefinedSeasons: any[] = [];
  selectedChart: string = '';

  constructor(
    private fb: FormBuilder,
    private router: Router,
    private contractDataService: ContractDataService
  ) {
    this.pricingForm = this.fb.group({
      currency: ['GBP', Validators.required],
      chartName: [''],
      seasons: this.fb.array([])
    });
  }

  ngOnInit() {
    this.loadPredefinedSeasons();
  }

  get seasons() {
    return this.pricingForm.get('seasons') as FormArray;
  }

  async loadPredefinedSeasons() {
    // Replace with actual API call
    this.predefinedSeasons = [
      { id: 1, ChartName: 'Default 2023', Level: 1, DateStart: '2023-01-01', DateEnd: '2023-03-31', Description: 'Low Season' },
      { id: 2, ChartName: 'Default 2023', Level: 2, DateStart: '2023-04-01', DateEnd: '2023-06-30', Description: 'Mid Season' },
      { id: 3, ChartName: 'Default 2023', Level: 3, DateStart: '2023-07-01', DateEnd: '2023-08-31', Description: 'High Season' },
      { id: 4, ChartName: 'Default 2023', Level: 2, DateStart: '2023-09-01', DateEnd: '2023-12-31', Description: 'Mid Season' },
    ];

    const chartNames = [...new Set(this.predefinedSeasons.map(season => season.ChartName))];
    if (chartNames.length > 0) {
      this.selectedChart = chartNames[0];
      this.handleChartSelection(this.selectedChart);
    }
  }

  handleChartSelection(chartName: string) {
    this.selectedChart = chartName;
    this.pricingForm.patchValue({ chartName });
    
    const selectedSeasons = this.predefinedSeasons
      .filter(season => season.ChartName === chartName)
      .map(season => this.fb.group({
        id: season.id,
        name: season.Description,
        startDate: season.DateStart,
        endDate: season.DateEnd,
        nightlyRate: ['', [Validators.required, Validators.min(0)]],
        weeklyRate: ['', [Validators.required, Validators.min(0)]]
      }));

    this.pricingForm.setControl('seasons', this.fb.array(selectedSeasons));
  }

  addCustomSeason() {
    const newId = Math.max(...this.seasons.value.map((s: any) => s.id), 0) + 1;
    this.seasons.push(this.fb.group({
      id: newId,
      name: ['Custom Season', Validators.required],
      startDate: ['', Validators.required],
      endDate: ['', Validators.required],
      nightlyRate: ['', [Validators.required, Validators.min(0)]],
      weeklyRate: ['', [Validators.required, Validators.min(0)]]
    }));
  }

  removeSeason(index: number) {
    this.seasons.removeAt(index);
  }

  calculateWeeklyRate(nightlyRate: number): number {
    return parseFloat((nightlyRate * 7).toFixed(2));
  }

  updateWeeklyRate(index: number) {
    const seasonGroup = this.seasons.at(index) as FormGroup;
    const nightlyRate = seasonGroup.get('nightlyRate')?.value;
    if (nightlyRate) {
      seasonGroup.patchValue({ weeklyRate: this.calculateWeeklyRate(nightlyRate) });
    }
  }

  onSubmit() {
    if (this.pricingForm.valid) {
      this.contractDataService.updatePricing(this.pricingForm.value);
      this.router.navigate(['/contract-summary']);
    }
  }

  onPrevious() {
    this.router.navigate(['/service-selection']);
  }
}
<ion-content class="ion-padding">
  <h1>Seasonal Pricing</h1>
  
  <form [formGroup]="pricingForm" (ngSubmit)="onSubmit()">
    <ion-item>
      <ion-label>Currency</ion-label>
      <ion-select formControlName="currency">
        <ion-select-option value="GBP">Pounds Sterling (£)</ion-select-option>
        <ion-select-option value="EUR">Euros (€)</ion-select-option>
      </ion-select>
    </ion-item>

    <ion-item>
      <ion-label>Select Predefined Season Chart</ion-label>
      <ion-select [(ngModel)]="selectedChart" [ngModelOptions]="{standalone: true}" (ionChange)="handleChartSelection($event.detail.value)">
        <ion-select-option *ngFor="let chartName of predefinedSeasons | uniqueChartNames" [value]="chartName">
          {{chartName}}
        </ion-select-option>
      </ion-select>
    </ion-item>

    <ion-list formArrayName="seasons">
      <ion-item-group *ngFor="let season of seasons.controls; let i = index" [formGroupName]="i">
        <ion-item-divider>
          <ion-label>
            <ion-input formControlName="name" placeholder="Season Name"></ion-input>
          </ion-label>
          <ion-button fill="clear" slot="end" (click)="removeSeason(i)" *ngIf="seasons.length > 1">
            <ion-icon name="trash-outline"></ion-icon>
          </ion-button>
        </ion-item-divider>
        <ion-item>
          <ion-label position="stacked">Start Date</ion-label>
          <ion-datetime formControlName="startDate" displayFormat="DD MMM YYYY"></ion-datetime>
        </ion-item>
        <ion-item>
          <ion-label position="stacked">End Date</ion-label>
          <ion-datetime formControlName="endDate" displayFormat="DD MMM YYYY"></ion-datetime>
        </ion-item>
        <ion-item>
          <ion-label position="stacked">Nightly Rate ({{pricingForm.get('currency')?.value === 'GBP' ? '£' : '€'}})</ion-label>
          <ion-input type="number" formControlName="nightlyRate" (ionChange)="updateWeeklyRate(i)"></ion-input>
        </ion-item>
        <ion-item>
          <ion-label position="stacked">Weekly Rate ({{pricingForm.get('currency')?.value === 'GBP' ? '£' : '€'}})</ion-label>
          <ion-input type="number" formControlName="weeklyRate" readonly></ion-input>
        </ion-item>
      </ion-item-group>
    </ion-list>

    <ion-button expand="block" (click)="addCustomSeason()">Add Custom Season</ion-button>

    <ion-button expand="block" (click)="onPrevious()">Previous</ion-button>
    <ion-button expand="block" type="submit" [disabled]="!pricingForm.valid">Next</ion-button>
  </form>
</ion-content>
